### ISSUE TITLE
lzstring dependency 1.0.4 doesn't publish wheels

### ISSUE THREAD

**Issue by basnijholt** [posit-dev/py-shinylive#44]
In this PR https://github.com/posit-dev/py-shinylive/pull/20 by @gadenbuie a dependency on lzstring=1.0.4 was introduced. However, that package doesn't publish Wheels: https://pypi.org/project/lzstring/1.0.4/#files.

This results in
```
Traceback (most recent call last):
  File "<exec>", line 378, in _start_app
  File "<exec>", line 277, in _install_requirements_from_dir
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 142, in install
    await transaction.gather_requirements(requirements)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 62, in add_requirement
    return await self.add_requirement_inner(Requirement(req))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 151, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 198, in _add_requirement_from_package_index
    await self.add_wheel(wheel, req.extras, specifier=str(req.specifier))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 236, in add_wheel
    await self.gather_requirements(wheel.requires(extras))
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 55, in gather_requirements
    await asyncio.gather(*requirement_promises)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 59, in add_requirement
    return await self.add_requirement_inner(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 151, in add_requirement_inner
    await self._add_requirement_from_package_index(req)
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 190, in _add_requirement_from_package_index
    wheel = find_wheel(metadata, req)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/micropip/transaction.py", line 281, in find_wheel
    raise ValueError(
ValueError: Can't find a pure Python 3 wheel for 'lzstring>=1.0.4'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
```

Reference app: https://github.com/basnijholt/adaptive-lighting/tree/main/webapp

**Comment by gadenbuie** [comment]
Are you using `shinylive` (the Python package) in your app? That you're also publishing with `shinylive` (the run-an-app-in-your-browser tech)?

If so, it's not really a use case we'd considered. Can you show us how you're using shinylive in the app?

If not, then it sounds like the presence of `shinylive` in your `requirements.txt` is the issue. I'd recommend moving that to a separate `requirements-dev.txt` or similar so that it isn't interpreted as a run-time requirement for your app.

**Comment by basnijholt** [comment]
Thank you! My misunderstanding was that I had to depend on `shinylive`. I set this up almost 2 years ago, and previously it seemed to work, so I didn't question whether it had to be a dependency. 

Thanks for your suggestion.

**Comment by basnijholt** [comment]
xref: https://basnijholt.github.io/adaptive-lighting/

The webapp works again, thanks for maintaining this awesome project!
